[project]
name = "selenium-geocoder"
version = "0.5.0"
authors = [
  { name="Hriday Keswani", email="hridaykeswnai@gmail.com" },
]
description = "Modularizing selenium code for getting coordinates from address of a place."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/hridayK/selenium-geocoder"
"Bug Tracker" = "https://github.com/hridayK/selenium-geocoder/issues"
[build-system]
requires = ["hatchling","selenium"]
build-backend = "hatchling.build"