[tool.poetry]
name = "aircraft-design"
version = "0.0.11"
description = "Condensed module for Aircraft Design"
authors = ["Nisus Aerodesign <ufsc.nisus@gmail.com>","Irisson Lima <irisson2203@gmail.com>"]
maintainers = ["Irisson Lima <irisson2203@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/aircraft-design/"
repository = "https://github.com/NisusAerodesign/aircraft-design"
packages = [{include = "aircraft_design"}]
keywords = ['aircraft', 'design', 'VLM', 'vortex lattice']

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
avlwrapper = "^0.3.4"
numpy = "^1.24.2"
matplotlib = "^3.6.3"
scipy = "^1.10.0"

[tool.poetry.group.dev.dependencies]
blue = "^0.9.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
