[project]
name = "cli-forge"
version = "0.0.1"
authors = [
  { name="Jonathan", email="jonathanfmaggio@gmail.com" },
]
description = "A tool for building simple CLIs"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "windows-curses; os_name == 'nt'"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/JmThrCreator/cli-forge"
"Bug Tracker" = "https://github.com/JmThrCreator/cli-forge/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"