[tool.poetry]
name = "solidipes"
version = "0.0.1"
description = "Python modules for DCSM"
authors = [
	"Son Pham-Ba <son.phamba@epfl.ch>",
	"Guillaume Anciaux <guillaume.anciaux@epfl.ch>"
]
license = ""
readme = "README.md"
packages = [{include = "solidipes"}]
homepage = "https://gitlab.com/groups/dcsm"
repository = "https://gitlab.com/dcsm/modules"
documentation = "https://solidipes.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.10"
meshio = {extras = ["all"], version = "^5.3.4"}
pyvista = "^0.38.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.4"
build = "^0.10.0"
pytest = "^7.2.1"
jupyter = "^1.0.0"
jupyterlab = "^3.6.1"
jupyterlab-widgets = "^3.0.5"
itkwidgets = "^0.32.5"
trame = "^2.2.6"
streamlit = "^1.17.0"
stpyvista = "^0.0.5"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.2.0"
myst-parser = "^0.18.1"

[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "semver"

[tool.black]
line-length = 79
