[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rounded_calculate"
version = "0.0.2"
authors = [
  { name="Vytautas Ruzgaila", email="DoNotContactMe@please.com" },
]
description = "Rounded calculator package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/TuringCollegeSubmissions/vruzga-DWWP.1"