[tool.poetry]
name = "project47a"
version = "0.1.0"
description = "Code name generator"
authors = ["Henryk Pl√∂tz <henryk@ploetzli.ch>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
isort = "^5.12.0"
black = "^23.1.0"
python-semantic-release = "^7.33.1"

[tool.semantic_release]
version_variable = [
    "project47/__init__.py:__version__",
    "pyproject.toml:tool.poetry.version"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
