[tool.poetry]
name = "cryptcha"
version = "0.0.2"
description = "Using my own cryptographic encryption technique with a hidden key, a Python-based package for building and validating secure captchas."
authors = ["beliefs <bio@fbi.ac>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.22.2"
replit = "^3.2.4"
Flask = "^2.2.0"
urllib3 = "^1.26.12"

[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = {extras = ["yapf", "rope", "pyflakes"], version = "^1.5.9"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"